version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: tp8-postgres
    environment:
      POSTGRES_USER: tp8user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: tp8db
    volumes:
      - ./server/migrations:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: tp8-server-local
    depends_on:
      - db
    environment:
      PORT: 8080
      DATABASE_URL: "postgres://tp8user:pass@db:5432/tp8db"
    ports:
      - "8082:8080"
    restart: unless-stopped